---
- name: Create web user.
  ansible.builtin.user:
    name: "{{ web_user }}"

- name: Create www directory.
  ansible.builtin.file:
    path: "{{ www_dir }}"
    state: directory
    mode: "0777"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"

- name: Install boom-http systemd service.
  ansible.builtin.template:
    src: boom-http.service
    dest: /etc/systemd/system/
    mode: "0644"

- name: Start and enabling boom-http service on boot.
  systemd:
    name: boom-http
    daemon_reload: yes
    state: started
    enabled: yes

- name: Copy files to serve.
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ www_dir }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0660
  loop: "{{ www_files }}"
